version: "3.9"  # optional since v1.27.0
services:
  app1:
    build:
      context: .
      dockerfile: ./prod/app1.dockerfile
    # ports:
    #   - 8000:3333
    command: node main.js
  app2:
    build:
      context: .
      dockerfile: ./prod/app2.dockerfile
    # ports:
    #   - 8001:3333
    command: node main.js
  nginx:
    image: nginx:latest
    volumes:
      - ./prod/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - 4000:4000




